
package uned.gestortiendadepartamentos;


public class EliminacionArticulosGUI extends javax.swing.JFrame {

    private GestorTienda gestor;

    public EliminacionArticulosGUI(GestorTienda gestor) {
        this.gestor = gestor;
        initComponents();
        cargarDepartamentos();

        tablaDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = tablaDep.getSelectedRow();
                if (fila != -1) {
                    cargarArticulos(fila);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminarArt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDep = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArt = new javax.swing.JTable();
        lblArt = new javax.swing.JLabel();
        lblDep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Artículos");

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        btnEliminarArt.setBackground(new java.awt.Color(249, 56, 39));
        btnEliminarArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarArt.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarArt.setText("Eliminar Artículo");
        btnEliminarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArtActionPerformed(evt);
            }
        });

        tablaDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDep.setShowGrid(true);
        tablaDep.getTableHeader().setResizingAllowed(false);
        tablaDep.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDep);

        tablaArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría"
            }
        ));
        tablaArt.setShowGrid(true);
        tablaArt.getTableHeader().setResizingAllowed(false);
        tablaArt.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaArt);

        lblArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArt.setForeground(new java.awt.Color(255, 255, 255));
        lblArt.setText("Artículos por departamento:");

        lblDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDep.setForeground(new java.awt.Color(255, 255, 255));
        lblDep.setText("Seleccione un departamento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDep, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblArt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarArt)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArtActionPerformed
       
        // Verifica que se haya seleccionado un departamento
        int fila = tablaDep.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un departamento.");
            return;
        }

        //llama al gestor para eliminar el artículo del departamento seleccionado
        Articulo eliminado = gestor.eliminarArticulo(fila);
        if (eliminado != null) { //si se recibe un articulo actualzia la tabla
            cargarArticulos(fila);
        } else { //si se recibe null, no hay artículos para eliminar
            javax.swing.JOptionPane.showMessageDialog(this, "No hay artículos para eliminar.");
        }

    }//GEN-LAST:event_btnEliminarArtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Método para cargar los departamentos en la tabla
    private void cargarDepartamentos() {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[] { "ID", "Nombre" }, 0);

        for (Departamento d : departamentos) {
            model.addRow(new Object[] { d.getId(), d.getNombre() });
        }

        tablaDep.setModel(model);
    }
    
    private void cargarArticulos(int index) {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        if (index < 0 || index >= departamentos.length)
            return;

        Articulo[] articulos = departamentos[index].obtenerArticulos();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[] { "ID", "Nombre", "Categoría" }, 0);

        for (Articulo a : articulos) {
            model.addRow(new Object[] { a.getId(), a.getNombre(), a.getCategoria() });
        }

        tablaArt.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarArt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArt;
    private javax.swing.JLabel lblDep;
    private javax.swing.JTable tablaArt;
    private javax.swing.JTable tablaDep;
    // End of variables declaration//GEN-END:variables
}
