
package uned.gestortiendadepartamentos;

import javax.swing.table.DefaultTableModel;

public class RegistroArticulosGUI extends javax.swing.JFrame {

    private GestorTienda gestor;

    public RegistroArticulosGUI(GestorTienda gestor) {
        this.gestor = gestor;
        initComponents();
        cargarDepartamentos();

        // carga los artículos al hacer clic en un departamento
        tablaDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = tablaDep.getSelectedRow();
                if (fila != -1) {
                    cargarArticulos(fila); 
                }
            }
        });

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane1 = new javax.swing.JScrollPane();
        tablaDep = new javax.swing.JTable();
        txtNombreArticulo = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        btnAgregarArtciulo = new javax.swing.JButton();
        scrollArticulos = new javax.swing.JScrollPane();
        tablaArt = new javax.swing.JTable();
        lblNombreArt = new javax.swing.JLabel();
        lblSeleccionarDep = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCategoria = new javax.swing.JLabel();
        lblArtGuardados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Artículo");

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        tablaDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDep.setShowGrid(true);
        tablaDep.getTableHeader().setResizingAllowed(false);
        tablaDep.getTableHeader().setReorderingAllowed(false);
        scrollPane1.setViewportView(tablaDep);

        txtNombreArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArticuloActionPerformed(evt);
            }
        });

        comboCategoria.setBackground(new java.awt.Color(42, 157, 143));
        comboCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(255, 255, 255));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa y accesorios ", "Electrónica", "Hogar y muebles ", "Belleza y cuidado personal ", "Deportes y aire libre ", "Juguetes y juegos ", "Alimentos y bebidas" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        btnAgregarArtciulo.setBackground(new java.awt.Color(42, 157, 143));
        btnAgregarArtciulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarArtciulo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarArtciulo.setText("Guardar articulo");
        btnAgregarArtciulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArtciuloActionPerformed(evt);
            }
        });

        tablaArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría"
            }
        ));
        tablaArt.setShowGrid(true);
        tablaArt.getTableHeader().setResizingAllowed(false);
        tablaArt.getTableHeader().setReorderingAllowed(false);
        scrollArticulos.setViewportView(tablaArt);

        lblNombreArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreArt.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreArt.setText("Nombre del articulo:");

        lblSeleccionarDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSeleccionarDep.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarDep.setText("Seleccione un departamento:");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría:");

        lblArtGuardados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArtGuardados.setForeground(new java.awt.Color(255, 255, 255));
        lblArtGuardados.setText("Articulos guardados:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreArticulo)
                            .addComponent(comboCategoria, 0, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(scrollArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarArtciulo)
                                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblArtGuardados, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreArt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addGap(18, 18, 18)
                .addComponent(lblSeleccionarDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarArtciulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblArtGuardados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArticuloActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    // Boton de guardar artículo
    private void btnAgregarArtciuloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarArtciuloActionPerformed
        
        // Verifica si se seleccionó un departamento de la tabla
        int fila = tablaDep.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un departamento.");
            return;
        }

        //Obtiene los datos del artículo
        String nombre = txtNombreArticulo.getText().trim();
        String categoria = comboCategoria.getSelectedItem().toString();

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el nombre del artículo.");
            return;
        }

        // Llama al método agregarArticulo del gestor, si recibe true, se agrega el artículo
        if (gestor.agregarArticulo(fila, nombre, categoria)) {

            txtNombreArticulo.setText(""); // Limpia el campo de texto
            comboCategoria.setSelectedIndex(0); // Reinicia el combo a la primera opción
            cargarArticulos(fila); // Refresca la tabla de artículos

        } else { // si recibe false
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo agregar. Cola llena.");
        }
    }                                                  

    /**
     * @param args the command line arguments
     */

    // Método para cargar los departamentos en la tabla
    private void cargarDepartamentos() {

        // Obtiene los departamentos del gestor y los carga en la tabla
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[] { "ID", "Nombre" }, 0);

            // Recorre los departamentos y los agrega al modelo de la tabla
        for (Departamento d : departamentos) {
            model.addRow(new Object[] { d.getId(), d.getNombre() });
        }

        tablaDep.setModel(model); // Actualiza la tabla de departamentos con el modelo
    }

    // Método para cargar artículos de un departamento seleccionado
    private void cargarArticulos(int index) { //se obtiene el índice del departamento seleccionado

        // Verifica que el índice sea válido
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        if (index < 0 || index >= departamentos.length)
            return;

        // Obtiene los artículos del departamento seleccionado
        Articulo[] articulos = departamentos[index].obtenerArticulos();
        DefaultTableModel model = new DefaultTableModel(new Object[] { "ID", "Nombre", "Categoría" }, 0);

        //Recorre los artículos y los agrega al modelo de la tabla
        for (Articulo a : articulos) {
            model.addRow(new Object[] { a.getId(), a.getNombre(), a.getCategoria() });
        }

        tablaArt.setModel(model); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArtciulo;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArtGuardados;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombreArt;
    private javax.swing.JLabel lblSeleccionarDep;
    private javax.swing.JScrollPane scrollArticulos;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTable tablaArt;
    private javax.swing.JTable tablaDep;
    private javax.swing.JTextField txtNombreArticulo;
    // End of variables declaration//GEN-END:variables
}
