
package Proyecto.gestortiendadepartamentos;

import javax.swing.JOptionPane;

public class EliminacionDepartamentosGUI extends javax.swing.JFrame {

    private GestorTienda gestor;

    public EliminacionDepartamentosGUI(GestorTienda gestor) {
        this.gestor = gestor;
        initComponents();
        cargarDepartamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sscrollTablaDep = new javax.swing.JScrollPane();
        tablaDep = new javax.swing.JTable();
        btnEliminarDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Departamentos");

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        tablaDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDep.setShowGrid(true);
        tablaDep.getTableHeader().setResizingAllowed(false);
        tablaDep.getTableHeader().setReorderingAllowed(false);
        sscrollTablaDep.setViewportView(tablaDep);

        btnEliminarDep.setBackground(new java.awt.Color(249, 56, 39));
        btnEliminarDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarDep.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDep.setText("Eliminar Departamento");
        btnEliminarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sscrollTablaDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(sscrollTablaDep, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarDepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarDepActionPerformed

        boolean eliminado = gestor.eliminarDepartamento(); // elimina el último departamento (LIFO)

        if (eliminado) { //si es true, se eliminó el departamento
            cargarDepartamentos(); // Refresca la tabla
        } else { //si es false, no se pudo eliminar
            JOptionPane.showMessageDialog(this,
                    "No se puede eliminar. El último departamento contiene artículos.");
        }

    }                                                                                            

    /**
     * @param args the command line arguments
     */

    private void cargarDepartamentos() {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[] { "ID", "Nombre" }, 0);

        for (Departamento d : departamentos) {
            model.addRow(new Object[] { d.getId(), d.getNombre() });
        }

        tablaDep.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarDep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane sscrollTablaDep;
    private javax.swing.JTable tablaDep;
    // End of variables declaration//GEN-END:variables
}
