/*Autor:  Anthony Mendoza Rivas.
Fecha  :  II Cuatrimestre 2025
Descripción:  Permite registrar departamentos, agregar articulos y gestionarlos */

package Proyecto.gestortiendadepartamentos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class MenuPrincipalGUI extends javax.swing.JFrame {

    public MenuPrincipalGUI() {
        initComponents();
        setupListeners(); // Configura los listeners de los botones
    }
    
    private GestorTienda gestor = new GestorTienda(); //Instancia del gestor de tienda
    
    private void setupListeners() {
        
        // Botón registrar departamentos
        btnRegistroDep.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new RegistroDepartamentosGUI(gestor).setVisible(true);
            }
        });
        
        // Botón registrar artículos
        btnRegistroArt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new RegistroArticulosGUI(gestor).setVisible(true);
            }
        });
        
        // Botón trasladar artículos
        btnTrasladoArt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new TrasladoArticulosGUI(gestor).setVisible(true);
            }
        });
        
        // Botón eliminar artículos
        btnEliminarArt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new EliminacionArticulosGUI(gestor).setVisible(true);
            }
        });
        
        // Botón eliminar departamentos
        btnEliminarDep.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new EliminacionDepartamentosGUI(gestor).setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnRegistroDep = new javax.swing.JButton();
        btnRegistroArt = new javax.swing.JButton();
        btnTrasladoArt = new javax.swing.JButton();
        btnEliminarArt = new javax.swing.JButton();
        btnEliminarDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestion de tienda por Departamentos");

        btnRegistroDep.setBackground(new java.awt.Color(42, 157, 143));
        btnRegistroDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistroDep.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroDep.setText("Registrar Departamentos");
        btnRegistroDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDepActionPerformed(evt);
            }
        });

        btnRegistroArt.setBackground(new java.awt.Color(42, 157, 143));
        btnRegistroArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistroArt.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroArt.setText("Registrar Artículos");

        btnTrasladoArt.setBackground(new java.awt.Color(255, 157, 35));
        btnTrasladoArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrasladoArt.setForeground(new java.awt.Color(255, 255, 255));
        btnTrasladoArt.setText("Trasladar Artículos");

        btnEliminarArt.setBackground(new java.awt.Color(249, 56, 39));
        btnEliminarArt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarArt.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarArt.setText("Eliminar Artículo");

        btnEliminarDep.setBackground(new java.awt.Color(249, 56, 39));
        btnEliminarDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarDep.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDep.setText("Eliminar Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrasladoArt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroArt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroDep, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminarArt, btnEliminarDep, btnRegistroArt, btnRegistroDep, btnTrasladoArt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroArt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrasladoArt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarArt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarDep)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEliminarArt, btnEliminarDep, btnRegistroArt, btnRegistroDep, btnTrasladoArt});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarArt;
    private javax.swing.JButton btnEliminarDep;
    private javax.swing.JButton btnRegistroArt;
    private javax.swing.JButton btnRegistroDep;
    private javax.swing.JButton btnTrasladoArt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
