
package Proyecto.gestortiendadepartamentos;

import javax.swing.JOptionPane;

public class RegistroDepartamentosGUI extends javax.swing.JFrame {

    private GestorTienda gestor; 

    public RegistroDepartamentosGUI(GestorTienda gestor) {
        this.gestor = gestor;
        initComponents();
        cargarDepartamentos();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDep = new javax.swing.JTable();
        txtDep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgrgarDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Departamentos");

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        jScrollPane1.setToolTipText("");

        tablaDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDep.setShowGrid(true);
        tablaDep.getTableHeader().setResizingAllowed(false);
        tablaDep.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDep);

        txtDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del departamento");

        btnAgrgarDep.setBackground(new java.awt.Color(42, 157, 143));
        btnAgrgarDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgrgarDep.setForeground(new java.awt.Color(255, 255, 255));
        btnAgrgarDep.setText("Guardar Departamento");
        btnAgrgarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrgarDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgrgarDep))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgrgarDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDepActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDepActionPerformed

    //Boton de agregar departamento
    private void btnAgrgarDepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgrgarDepActionPerformed
        
        String nombre = txtDep.getText().trim();

        // Verifica si el campo de texto está vacío
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el departamento.");
            return;
        }

        //llama al método agregarDepartamento del gestor 
        if (gestor.agregarDepartamento(nombre)) {
            cargarDepartamentos();
            txtDep.setText(""); // Limpia el campo de texto
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar. La pila está llena.");
        }

    }                                            

    /**
     * @param args the command line arguments
     */
    
    // cargar el departamento en la tabla
    private void cargarDepartamentos() {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[] { "ID", "Nombre" }, 0);

        for (Departamento d : departamentos) {
            model.addRow(new Object[] { d.getId(), d.getNombre() });
        }

        tablaDep.setModel(model); // Actualiza la tabla con los departamentos
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrgarDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDep;
    private javax.swing.JTextField txtDep;
    // End of variables declaration//GEN-END:variables
}
