
package Proyecto.gestortiendadepartamentos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TrasladoArticulosGUI extends javax.swing.JFrame {

    private GestorTienda gestor;

    public TrasladoArticulosGUI(GestorTienda gestor) {
        this.gestor = gestor;
        initComponents();
        cargarDepartamentos();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollTablaOrigen = new javax.swing.JScrollPane();
        tablaDepOrigen = new javax.swing.JTable();
        scrollTablaDestino = new javax.swing.JScrollPane();
        tablaDepDestino = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnTraslado = new javax.swing.JButton();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        scrollTablaResultado = new javax.swing.JScrollPane();
        tablaResultado = new javax.swing.JTable();
        lblArtDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 52, 72));

        tablaDepOrigen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDepOrigen.setShowGrid(true);
        tablaDepOrigen.getTableHeader().setResizingAllowed(false);
        tablaDepOrigen.getTableHeader().setReorderingAllowed(false);
        scrollTablaOrigen.setViewportView(tablaDepOrigen);

        tablaDepDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaDepDestino.setShowGrid(true);
        tablaDepDestino.getTableHeader().setResizingAllowed(false);
        tablaDepDestino.getTableHeader().setReorderingAllowed(false);
        scrollTablaDestino.setViewportView(tablaDepDestino);

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        btnTraslado.setBackground(new java.awt.Color(42, 157, 143));
        btnTraslado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTraslado.setForeground(new java.awt.Color(255, 255, 255));
        btnTraslado.setText("Trasladar Artículos");
        btnTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladoActionPerformed(evt);
            }
        });

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblOrigen.setText("Departamento de Origen");

        lblDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblDestino.setText("Departamento de Destino");

        tablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaResultado.setShowGrid(true);
        tablaResultado.getTableHeader().setResizingAllowed(false);
        tablaResultado.getTableHeader().setReorderingAllowed(false);
        scrollTablaResultado.setViewportView(tablaResultado);

        lblArtDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArtDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblArtDestino.setText("Articulos en el destino:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablaResultado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArtDestino)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnTraslado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                                        .addComponent(scrollTablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(scrollTablaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblOrigen)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblDestino)))
                                .addComponent(jSeparator1)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigen)
                    .addComponent(lblDestino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTablaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTraslado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblArtDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTablaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón para trasladar artículos
    private void btnTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladoActionPerformed
        
        // Verifica que se hayan seleccionado los departamentos en ambas tablas
        int filaOrigen = tablaDepOrigen.getSelectedRow();
        int filaDestino = tablaDepDestino.getSelectedRow();

        if (filaOrigen == -1 || filaDestino == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione ambos departamentos.");
            return;
        }

        if (filaOrigen == filaDestino) {
            JOptionPane.showMessageDialog(this, "El origen y el destino deben ser diferentes.");
            return;
        }
      
        // Llama al método trasladarArticulos del gestor
        boolean exito = gestor.trasladarArticulos(filaOrigen, filaDestino);
        if (exito) {
            cargarArticulosDestino(filaDestino);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo trasladar. Verifique que existan artículos y espacio en los departamentos.");
        }
        
    }//GEN-LAST:event_btnTrasladoActionPerformed

    /**
     * @param args the command line arguments
     */

    private void cargarDepartamentos() {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        DefaultTableModel modelOrigen = new DefaultTableModel(new Object[] { "ID", "Nombre" }, 0);
        DefaultTableModel modelDestino = new DefaultTableModel(new Object[] { "ID", "Nombre" }, 0);

        for (Departamento d : departamentos) {
            Object[] fila = new Object[] { d.getId(), d.getNombre() };
            modelOrigen.addRow(fila);
            modelDestino.addRow(fila);
        }

        tablaDepOrigen.setModel(modelOrigen);
        tablaDepDestino.setModel(modelDestino);
    }

    private void cargarArticulosDestino(int index) {
        Departamento[] departamentos = gestor.obtenerDepartamentos();
        if (index < 0 || index >= departamentos.length)
            return;

        Articulo[] articulos = departamentos[index].obtenerArticulos();
        DefaultTableModel model = new DefaultTableModel(new Object[] { "ID", "Nombre", "Categoría" }, 0);

        for (Articulo a : articulos) {
            model.addRow(new Object[] { a.getId(), a.getNombre(), a.getCategoria() });
        }

        tablaResultado.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraslado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArtDestino;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JScrollPane scrollTablaDestino;
    private javax.swing.JScrollPane scrollTablaOrigen;
    private javax.swing.JScrollPane scrollTablaResultado;
    private javax.swing.JTable tablaDepDestino;
    private javax.swing.JTable tablaDepOrigen;
    private javax.swing.JTable tablaResultado;
    // End of variables declaration//GEN-END:variables
}
